//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioinformaticsRosalindStrongHold.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioinformaticsRosalindStrongHold.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA K
        ///AAC N
        ///AAG K
        ///AAU N
        ///ACA T
        ///ACC T
        ///ACG T
        ///ACU T
        ///AGA R
        ///AGC S
        ///AGG R
        ///AGU S
        ///AUA I
        ///AUC I
        ///AUG M
        ///AUU I
        ///CAA Q
        ///CAC H
        ///CAG Q
        ///CAU H
        ///CCA P
        ///CCC P
        ///CCG P
        ///CCU P
        ///CGA R
        ///CGC R
        ///CGG R
        ///CGU R
        ///CUA L
        ///CUC L
        ///CUG L
        ///CUU L
        ///GAA E
        ///GAC D
        ///GAG E
        ///GAU D
        ///GCA A
        ///GCC A
        ///GCG A
        ///GCU A
        ///GGA G
        ///GGC G
        ///GGG G
        ///GGU G
        ///GUA V
        ///GUC V
        ///GUG V
        ///GUU V
        ///UAA 
        ///UAC Y
        ///UAG 
        ///UAU Y
        ///UCA S
        ///UCC S
        ///UCG S
        ///UCU S
        ///UGA 
        ///UGC C
        ///UGG W
        ///UGU C
        ///UUA L
        ///UUC F
        ///UUG L
        ///UUU F.
        /// </summary>
        internal static string RNA_PROTEINS_TABLE {
            get {
                return ResourceManager.GetString("RNA_PROTEINS_TABLE", resourceCulture);
            }
        }
    }
}
